eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  cloud:
    discovery:
      enabled: false

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans