spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: http://client-service:8090
          predicates:
            - Path=/api/clients/**, /client-service/**
        - id: product-service
          uri: http://product-service:8050
          predicates:
            - Path=/api/devices/**, /api/units/**, /api/games/**, /product-service/**
        - id: rental-service
          uri: http://rental-service:8070
          predicates:
            - Path=/api/rentals/**, /rental-service/**