spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/rental
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8070

application:
  config:
    client-url: http://localhost:8222/api/clients
    device-url: http://localhost:8222/api/units
    game-url: http://localhost:8222/api/games

resilience4j:
  ratelimiter:
    instances:
      rentalControllerLimiter:
        baseConfig: default
  time-limiter:
    instances:
      rentalTimeLimiter:
        baseConfig: default

openapi:
  title: Rental Service API
  description: Rental Service API docs.
  version: 1.0.0
  url: http://localhost:{server.port}
springdoc:
  api-docs:
    path: /rental-service/v3/api-docs
  swagger-ui:
    path: /rental-service/swagger-ui.html